[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
evm_version = "paris"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = true

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

[etherscan]
# Add your etherscan API key here for verification

[rpc_endpoints]
# Add your RPC endpoints here
